image: "rust:latest"

stages:
 - test
 - build

test:
 stage: test
 script:
  - rustc --version
  - cargo --version
  - cargo check

build:
  stage: build
  only:
    - tags
  script:
    - cargo build --release --locked
  artifacts:
    paths:
      - target/release/organize-rt

cache:
  paths:
    - cargo/
    - target/
