image: "rust:latest"

stages:
 - test
 - build

test:
 stage: test
 script:
  - rustc --version
  - cargo --version
  - rustup component add clippy
  - cargo clippy -- -W clippy::pedantic -W clippy::all -W clippy::cargo

build:
  stage: build
  only:
    - tags
  script:
    - cargo build --release
    - mv target/release/organize-rt ./linux64
    - cargo login $CARGO_LOGIN
    - cargo publish
  artifacts:
    paths:
      - ./linux64

cache:
  paths:
    - cargo/
    - target/
